# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mb_protocol_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mb_protocol_enums.proto\x12\x15wmb.proto.mb_protocol*=\n\nModbusMode\x12\x16\n\x12MODBUS_MODE_MASTER\x10\x00\x12\x17\n\x13MODBUS_MODE_SNIFFER\x10\x01*=\n\x0f\x41ntennaSettings\x12\x14\n\x10\x41NTENNA_INTERNAL\x10\x00\x12\x14\n\x10\x41NTENNA_EXTERNAL\x10\x01*R\n\nModbusPort\x12\x19\n\x15MODBUS_PORT_UNDEFINED\x10\x00\x12\x14\n\x10MODBUS_PORT_ZERO\x10\x01\x12\x13\n\x0fMODBUS_PORT_ONE\x10\x02*\xde\x01\n\nModbusBaud\x12\x19\n\x15MODBUS_BAUD_UNDEFINED\x10\x00\x12\x14\n\x10MODBUS_BAUD_4800\x10\x0c\x12\x14\n\x10MODBUS_BAUD_9600\x10\r\x12\x15\n\x11MODBUS_BAUD_19200\x10\x0e\x12\x15\n\x11MODBUS_BAUD_28800\x10\x0f\x12\x15\n\x11MODBUS_BAUD_38400\x10\x10\x12\x15\n\x11MODBUS_BAUD_57600\x10\x11\x12\x15\n\x11MODBUS_BAUD_76800\x10\x12\x12\x16\n\x12MODBUS_BAUD_115200\x10\x13\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mb_protocol_enums_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODBUSMODE._serialized_start=50
  _MODBUSMODE._serialized_end=111
  _ANTENNASETTINGS._serialized_start=113
  _ANTENNASETTINGS._serialized_end=174
  _MODBUSPORT._serialized_start=176
  _MODBUSPORT._serialized_end=258
  _MODBUSBAUD._serialized_start=261
  _MODBUSBAUD._serialized_end=483
# @@protoc_insertion_point(module_scope)
