# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mb_protocol_answers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mb_protocol_enums_pb2 as mb__protocol__enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mb_protocol_answers.proto\x12\x15wmb.proto.mb_protocol\x1a\x17mb_protocol_enums.proto\"I\n\x08\x41\x63kFrame\x12\x37\n\x0b\x61\x63knowladge\x18\x02 \x01(\x0e\x32\".wmb.proto.mb_protocol.AcknowladgeJ\x04\x08\x01\x10\x02\"6\n\x17PeriodicalConfiguration\x12\x15\n\rconfiguration\x18\x02 \x01(\rJ\x04\x08\x01\x10\x02\"\xfb\x03\n\x13\x44iagnosticsAnsFrame\x12\x18\n\x10\x66irmware_version\x18\x02 \x01(\r\x12\x11\n\tdevice_id\x18\x03 \x01(\r\x12\x16\n\x0etransport_type\x18\x04 \x01(\r\x12\x18\n\x10last_reset_cause\x18\x05 \x01(\r\x12\x1a\n\x12last_reset_trigger\x18\x06 \x01(\r\x12\x1a\n\x12last_fault_address\x18\x07 \x01(\r\x12\x36\n\x0b\x64\x65vice_mode\x18\x08 \x01(\x0e\x32!.wmb.proto.mb_protocol.ModbusMode\x12@\n\x10\x61ntenna_settings\x18\t \x01(\x0e\x32&.wmb.proto.mb_protocol.AntennaSettings\x12\x0e\n\x06uptime\x18\n \x01(\r\x12\x36\n\x0b\x62\x61ud_port_0\x18\x0b \x01(\x0e\x32!.wmb.proto.mb_protocol.ModbusBaud\x12\x36\n\x0b\x62\x61ud_port_1\x18\x0c \x01(\x0e\x32!.wmb.proto.mb_protocol.ModbusBaud\x12M\n\x15modbus_configurations\x18\r \x03(\x0b\x32..wmb.proto.mb_protocol.PeriodicalConfigurationJ\x04\x08\x01\x10\x02\"\x86\x01\n\x13ModbusResponseFrame\x12\x36\n\x0bmodbus_port\x18\x02 \x01(\x0e\x32!.wmb.proto.mb_protocol.ModbusPort\x12\x1b\n\x13\x63onfiguration_index\x18\x03 \x01(\r\x12\x14\n\x0cmodbus_frame\x18\x04 \x01(\x0cJ\x04\x08\x01\x10\x02\"\xed\x01\n\x0b\x41nswerFrame\x12\x34\n\tack_frame\x18\x01 \x01(\x0b\x32\x1f.wmb.proto.mb_protocol.AckFrameH\x00\x12K\n\x15\x64iagnostics_ans_frame\x18\x02 \x01(\x0b\x32*.wmb.proto.mb_protocol.DiagnosticsAnsFrameH\x00\x12K\n\x15modbus_response_frame\x18\x03 \x01(\x0b\x32*.wmb.proto.mb_protocol.ModbusResponseFrameH\x00\x42\x0e\n\x0c\x61nswer_frame*R\n\x0b\x41\x63knowladge\x12\x17\n\x13\x41\x43KNOWLADGE_UNKNOWN\x10\x00\x12\x14\n\x0f\x41\x43KNOWLADGE_ACK\x10\xaa\x01\x12\x14\n\x10\x41\x43KNOWLADGE_NACK\x10wb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mb_protocol_answers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACKNOWLADGE._serialized_start=1095
  _ACKNOWLADGE._serialized_end=1177
  _ACKFRAME._serialized_start=77
  _ACKFRAME._serialized_end=150
  _PERIODICALCONFIGURATION._serialized_start=152
  _PERIODICALCONFIGURATION._serialized_end=206
  _DIAGNOSTICSANSFRAME._serialized_start=209
  _DIAGNOSTICSANSFRAME._serialized_end=716
  _MODBUSRESPONSEFRAME._serialized_start=719
  _MODBUSRESPONSEFRAME._serialized_end=853
  _ANSWERFRAME._serialized_start=856
  _ANSWERFRAME._serialized_end=1093
# @@protoc_insertion_point(module_scope)
